compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'yes'
fsdp_config:
  xla: false 
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_POST
  fsdp_forward_prefetch: true
  fsdp_offload_params: true
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true 
  fsdp_use_orig_params: false   
  # fsdp_activation_checkpointing: true
  fsdp_activation_offloading: true
  # fsdp_activation_offloading: false
  fsdp_compute_dtype: bf16
  fsdp_4bit_optimizer: true
  fsdp_gradient_sharding: true
  fsdp_weight_sharding: true
  fsdp_use_mem_efficient_gradient_sharding: true
machine_rank: 0
main_process_port: 29501
main_training_function: main
mixed_precision: bf16
num_machines: 1 # 128 
num_processes: 8 # 512
rdzv_backend: c10d
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false