# Model arguments
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Llama-8B
model_revision: main
torch_dtype: bfloat16
# attn_implementation: flash_attention_2
use_liger_kernel: true
bf16: true
tf32: true
output_dir: /disk/u/harshraj/CotIF/models/R1-Distill-Llama-8B-PEFT-cotroller_dataset-openmath_1m_all_cotif-v6
# output_dir: /share/u/harshraj/CotIF/models/R1-Distill-Llama-8B-PEFT-cotroller_dataset-bespoke_52k_cotif-v6
# output_dir: /share/u/harshraj/CotIF/models/R1-Distill-Llama-8B-PEFT-cotroller_dataset-open_thoughts_mix_cotif_0.25-v6

# Dataset arguments
dataset_id_or_path: /disk/u/harshraj/CotIF/data/cotroller_dataset-openmath-1m-all_cotif-v6.json
# dataset_id_or_path: /share/u/harshraj/CotIF/data/cotroller_dataset-bespoke_mix-52k_all_cotif-v6.json
# dataset_id_or_path: /share/u/harshraj/CotIF/data/cotroller_dataset-bespoke_mix-v6.json
# dataset_id_or_path: /share/u/harshraj/CotIF/data/cotroller_dataset-open_thoughts_mix_cotif_0.25-v6.json
max_seq_length: 8000
packing: true

# Save merged weights option
save_merged_weights: true  # Set to true to save the merged weights

# LoRA arguments
use_peft: true
# load_in_4bit: true
lora_target_modules: "all-linear"
# important as we need to train the special tokens for the chat template of llama 
lora_modules_to_save: ["lm_head", "model.embed_tokens"] # you might need to change this for qwen or other models
lora_r: 16
lora_alpha: 16

# Training arguments
# num_samples: 100
num_train_epochs: 2
# max_steps: 10
per_device_train_batch_size: 12
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-5
lr_scheduler_type: constant
warmup_ratio: 0.03

# Logging arguments
logging_strategy: steps
logging_steps: 5
report_to:
- tensorboard
save_strategy: "epoch"
seed: 42

# Hugging Face Hub 
push_to_hub: false
# hub_model_id: llama-3-1-8b-math-orca-qlora-10k-ep1 # if not defined same as output_dir
hub_strategy: every_save
